version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    build:
      dockerfile: ./db.Dockerfile
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080


  backend:
    container_name: backend
    build:
      dockerfile: ./backend.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    command: sh -c "python manage.py wait_for_db --settings config.docker &&
                    python manage.py migrate --settings config.docker && 
                    python manage.py runserver 0.0.0.0:8000 --settings config.docker"