# Generated by Django 4.1.6 on 2023-03-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantmon', '0004_devicereadings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereadings',
            options={'ordering': ['-timestamp']},
        ),
    ]
